import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import Providers from './providers';
import './globals.css';

const source_sans = Source_Sans_3({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={source_sans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
